/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-15 08:11:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1713168594441L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1713168594441L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>수강신청 페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("header h2 {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #009aff;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("header nav {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	background-color: #00229a;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: start;\r\n");
      out.write("	gap: 30px;\r\n");
      out.write("	padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("header nav *{\r\n");
      out.write("	color: white;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("#container {\r\n");
      out.write("	min-height: calc(100vh - 100px - 50px);\r\n");
      out.write("	background-color: #ccc;\r\n");
      out.write("	padding-top: 75px;\r\n");
      out.write("}\r\n");
      out.write("#cont-title {\r\n");
      out.write("	padding: 10px 15px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#inner-container {\r\n");
      out.write("	display:flex;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("	align-items:center;\r\n");
      out.write("	justify-content:center;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("padding: 5px 15px;\r\n");
      out.write("}\r\n");
      out.write("td input {\r\n");
      out.write("	padding: 5px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<h2>수강신청 도우미 사이트</h2>\r\n");
      out.write("		<nav>\r\n");
      out.write("			<a href=\"./showList.jsp\">교과목목록 조회/수정</a>\r\n");
      out.write("			<a href=\"./insert.jsp\">교과목 추가</a>\r\n");
      out.write("			<a href=\"./index.jsp\">홈으로</a>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<section id=\"container\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2 id='cont-title'>\r\n");
      out.write("	수강신청 관리 프로그램\r\n");
      out.write("</h2>\r\n");
      out.write("<p style='padding: 30px'>\r\n");
      out.write("\r\n");
      out.write("1. 총 10개의 교과목이 있습니다.<br>\r\n");
      out.write("\r\n");
      out.write("2. 교과목 목록을 확인하려면 교과목 목록 조회/수정 메뉴를 클릭하세요.<br>\r\n");
      out.write("\r\n");
      out.write("3. 교과목을 추가하려면 교과목 추가 메뉴를 클릭하세요.<br>\r\n");
      out.write("\r\n");
      out.write("4. 교과목을 수정하려면 교과목 목록 메뉴에서 과목코드를 클릭하세요.<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("	<style>\r\n");
      out.write("	footer {\r\n");
      out.write("	background-color: #00229a;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("	<footer>\r\n");
      out.write("		Copyright &copy; 서울문화고등학교 사물인터넷과 All Right Reserved\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
